name: github pages devel

on:
  push:
    branches:
      - devel

jobs:
  deploy:
    runs-on: ubuntu-18.04
    environment: github-pages-devel
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: hugo --minify -s exampleSite
        env:
          HUGO_ENVIRONMENT: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./exampleSite/public
          publish_branch: gh-pages-devel
